### ISSUE TITLE
State value to set is invalid

### ISSUE THREAD

**Issue by Michelzahn** [iobroker-community-adapters/ioBroker.fhem#71] opened 2020-06-06 20:47 UTC
Error message in the log file:
fhem.0 (7881) This value will not be set in future versions. Please report this to the developer.
fhem.0 (7881) State value to set is invalid for fhem.0.Steckdose_Wohnzimmer_links.Wifi_AP: The state property "ts" has the wrong type "undefined" (should be "number")!

**Comment by LausiD** [comment] 2020-06-07 12:33
thx for the report
I guess you're using V1.3.0 of stable?
https://github.com/iobroker-community-adapters/ioBroker.fhem/issues/70

**Comment by Michelzahn** [comment] 2020-06-07 12:36
Hi,

yes, the adapter version 1.3.0. Iobroker is running on a Raspberry 4 with Buster and node v10.20.1.

Kr
Niko
________________________________
Von: LausiD <notifications@github.com>
Gesendet: Sonntag, 7. Juni 2020 14:34
An: iobroker-community-adapters/ioBroker.fhem <ioBroker.fhem@noreply.github.com>
Cc: Michelzahn <michelzahn@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [iobroker-community-adapters/ioBroker.fhem] State value to set is invalid (#71)


thx for the report
I guess you're using V1.3.0 of stable?
#70<https://github.com/iobroker-community-adapters/ioBroker.fhem/issues/70>

**Comment by LausiD** [comment] 2020-06-07 12:48
Hi Niko,

ok pls update V1.5.2 from github 

best regards
LausiD

**Comment by MarkusEder** [comment] 2020-06-16 13:52
Hi LausiD,

V1.3.0 was working ok, just the above messages so I upgraded to 1.5.2 on two different Machines (a PI3 Node.js    v12.18.0 and a Pi4 with Node.js: v14.4.0). On both installations I get these Logentries after installing V1.5.2

host.fhempi | 2020-06-16 15:15:39.878 | info | Restart adapter system.adapter.fhem.0 because enabled
-- | -- | -- | --
host.fhempi | 2020-06-16 15:15:39.878 | error | instance system.adapter.fhem.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.fhempi | 2020-06-16 15:15:39.878 | error | Caught by controller[0]:     at internal/main/run_main_module.js:17:47
host.fhempi | 2020-06-16 15:15:39.878 | error | Caught by controller[0]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
host.fhempi | 2020-06-16 15:15:39.877 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
host.fhempi | 2020-06-16 15:15:39.877 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:986:32)
host.fhempi | 2020-06-16 15:15:39.877 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
host.fhempi | 2020-06-16 15:15:39.877 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:1102:27)
host.fhempi | 2020-06-16 15:15:39.876 | error | Caught by controller[0]:     at wrapSafe (internal/modules/cjs/loader.js:1054:16)
host.fhempi | 2020-06-16 15:15:39.876 | error | Caught by controller[0]: SyntaxError: missing ) after argument list
host.fhempi | 2020-06-16 15:15:39.876 | error | Caught by controller[0]:                             ^^^^^^^^^^^^^
host.fhempi | 2020-06-16 15:15:39.875 | error | Caught by controller[0]:         eventNOK(fn, event, 'no channel 'only parts[0] = ' + parts[0], 'warn', 'unknown');
host.fhempi | 2020-06-16 15:15:39.875 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.fhem/main.js:2317
host.fhempi | 2020-06-16 15:15:39.456 | info | instance system.adapter.fhem.0 started with pid 5859


any Idea, going back to V1.3.0 no errors, but these logentries
fhem.0 | 2020-06-16 15:49:53.100 | warn | (6590)  State value to set is invalid for fhem.0.Spielzimmer.battery: The state  property "ts" has the wrong type "undefined" (should be "number")!
-- | -- | -- | --
fhem.0 | 2020-06-16 15:49:52.562 | warn | (6590) This value will not be set in future versions. Please report this to the developer.
fhem.0 | 2020-06-16 15:49:52.561 | warn | (6590)  State value to set is invalid for fhem.0.Spielzimmer.temperature: The  state property "ts" has the wrong type "undefined" (should be "number")!
fhem.0 | 2020-06-16 15:49:52.553 | warn | (6590) This value will not be set in future versions. Please report this to the developer.`

**Comment by LausiD** [comment] 2020-06-19 15:44
@MarkusEder 
pls check update 1.5.2 buildDate 18.06.20 from github

**Comment by FrodoBernd** [comment] 2020-06-20 23:30
Hello, i had the same problem just after the js update.
now it is fixed with the latest version.
1.5.2 buildDate 06/18/20

Many thanks

**Comment by MarkusEder** [comment] 2020-06-23 09:12
THX LausiD, I can confirm it works with both Node.js v12.18.0 and v14.4.0

**Comment by LausiD** [comment] 2020-06-23 14:24
@MarkusEder @FrodoBernd 
Thanks for the feedback :-)

**Closed by LausiD** 2020-06-23 14:24 UTC
